exports.envData = 
{
    "ENVIRONMENT_NAME": "##ENVIRONMENT_NAME_VAL##",
    "SHOP_CFDISTRIB_WSJ": "##SHOP_CFDISTRIB_WSJ_VAL##",
    "SHOP_CFDISTRIB_BAR": "##SHOP_CFDISTRIB_BAR_VAL##",
    "VANITY_CFDISTRIB_WSJ": "##VANITY_CFDISTRIB_WSJ_VAL##",
    "CF_AWS_ACCOUNT_NUMBER" : "##CF_AWS_ACCTNUMBER_VAL##"
};